### ISSUE TITLE
FixedWidthInteger in Swift 4

### ISSUE THREAD

**Issue by andreyz** [mikeash/BinaryCoder#1]
Have you had time to look at Swift 4 migration issues?

`BinaryEncoder.swift:70:23: Protocol 'FixedWidthInteger' can only be used as a generic constraint because it has Self or associated type requirements`

`BinaryDecoder.swift:109:26: Protocol 'FixedWidthInteger' can only be used as a generic constraint because it has Self or associated type requirements`

**Comment by mikeash** [comment]
Thanks for bringing this up. I fixed it for Swift 4. Unfortunately that meant abandoning the nice trick with `FixedWidthInteger`. But it works again!
