### ISSUE TITLE
Does it support encode to Data and decode from Data?

### ISSUE THREAD

**Issue by diuming** [mikeash/BinaryCoder#3]
Does it support encode to Data and decode from Data?
Does it supoort NSRect, NSSize, NSPoint?
BinaryEncoder.encode() -> Data
BinaryDecoder.decode(BinaryCodable, data: Data)

**Comment by mikeash** [comment]
It doesn't directly deal with `Data`, but it's easy to convert between `Data` and `[UInt8]`.

I'm not sure about the various `NS` structs. Try it and see!
